/* global console, URL */
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const root = resolve(new URL('.', import.meta.url).pathname);
const manifest = JSON.parse(await readFile(resolve(root, 'manifest.json'), 'utf8'));
assert.equal(manifest.manifest_version, 3);
assert.ok(manifest.permissions.includes('activeTab'));
assert.ok(manifest.permissions.includes('scripting'));
assert.ok(manifest.permissions.includes('alarms'));
assert.equal(manifest.content_scripts, undefined);
assert.equal(manifest.background.service_worker, 'background.js');
const popup = await readFile(resolve(root, 'popup.js'), 'utf8');
const content = await readFile(resolve(root, 'content.js'), 'utf8');
const background = await readFile(resolve(root, 'background.js'), 'utf8');
const popupHtml = await readFile(resolve(root, 'popup.html'), 'utf8');
assert.match(popup, /rawUpload: 'disabled'/);
assert.match(background, /SHA-256/);
assert.match(popup, /selected\.thumbnail/);
assert.doesNotMatch(popup, /selected\.src|selected\.thumbnail\s*\|\|/);
assert.match(content, /CONTRIBUTOR_START_PICKER/);
assert.match(content, /CONTRIBUTOR_CONFIRM_DOCUMENT/);
assert.match(content, /const MAX_PICKER_CANDIDATES = 5000/);
assert.match(content, /Math\.min\(document\.images\.length, MAX_PICKER_CANDIDATES\)/);
assert.match(content, /candidates\.length < MAX_PICKER_CANDIDATES/);
assert.match(content, /pickerMaxCandidateCountObserved/);
assert.ok(content.indexOf('clear();') < content.indexOf("type: 'CONTRIBUTOR_IMAGE_SELECTED'"));
assert.match(content, /Tab moves/);
assert.match(background, /captureVisibleTab/);
assert.match(background, /before\?\.id !== sender\.tab\.id/);
assert.match(background, /after\?\.id !== sender\.tab\.id/);
assert.match(background, /await confirmDocument\(\)/);
assert.match(background, /contributor-selection-expiry/);
assert.match(popup, /score < 65/);
assert.match(popup, /score >= 65/);
assert.match(popup, /selectionIsFresh/);
assert.match(popup, /scheduleExpiry/);
assert.match(popupHtml, /seroslop\.svg/);
assert.doesNotMatch(`${popup}\n${content}\n${background}`, /fetch\s*\(|XMLHttpRequest|github\.com|huggingface\.co|https?:\/\//);
console.log('contributor validation: PASS');
